server:
  name: 'test.com'

db:
  database: 'test_com'
  ssl: false
#  user: 'test'
#  password: 'test'

lang:
  languages:
    - 'en'
    - 'ru'
    - 'uk'

app:
  autoload:
    - 'pytsite.auth_ui'
    - 'pytsite.auth_log'
    - 'pytsite.content'
#    - 'pytsite.addthis'
#    - 'pytsite.disqus'
#    - 'pytsite.fb'
#  links:
#    - 'https://facebook.com'
#    - 'https://twitter.com'
#    - 'https://plus.google.com'
#    - 'https://tumblr.com'
#    - 'https://livejournal.com'
#    - 'info@test.com'
#  launch_year: '2015'

routes:
  '/':
    _name: 'app.ep.home'

  '/section/<string:term_alias>':
    _name: 'app.article.index.section'
    _call: 'pytsite.content.ep.index'
    model: 'article'
    term_field: 'section'

  '/tag/<string:term_alias>':
    _name: 'app.article.index.tag'
    _call: 'pytsite.content.ep.index'
    model: 'article'
    term_field: 'tags'

content:
  sitemap:
    models:
      - 'article'
      - 'page'
  feed:
    models:
      - 'article'

#addthis:
#  pub_id: ''

#disqus:
#  short_name: ''
#  api_secret: ''

#fb:
#  app_id: ''
#  app_secret: ''
