server:
  name: 'test.com'

db:
  database: 'test_com'
  ssl: false
#  user: 'test'
#  password: 'test'

lang:
  languages:
    - 'en'
    - 'ru'
    - 'uk'

app:
  autoload:
    - 'pytsite.auth_ulogin'
    - 'pytsite.auth_log'
    - 'pytsite.content'
    - 'pytsite.content_import'
    - 'pytsite.disqus'
    - 'pytsite.addthis'
