server_name: test.com

db:
  database: test_com
#  user: 'test'
#  password: 'test'

languages: [en, ru, uk]

autoload:
  - pytsite.auth_ulogin
  - pytsite.auth_log
  - pytsite.content
  - pytsite.disqus
  - pytsite.addthis
