server:
  name: 'test.com'

db:
  database: 'test_com'
  ssl: false
#  user: 'test'
#  password: 'test'

lang:
  languages:
    - 'en'
    - 'ru'
    - 'uk'

app:
  autoload:
    - 'pytsite.auth_ui'
    - 'pytsite.auth_log'
    - 'pytsite.content'
    - 'pytsite.ulogin'
#    - 'pytsite.addthis'
#    - 'pytsite.disqus'
  links:
    - 'https://facebook.com'
    - 'https://twitter.com'
    - 'https://plus.google.com'
    - 'https://tumblr.com'
    - 'https://livejournal.com'
    - 'info@test.com'
  launch_year: '2016'

content:
  sitemap:
    models:
      - 'article'
      - 'page'
  feed:
    models:
      - 'article'

#addthis:
#  pub_id: ''

#disqus:
#  short_name: ''
#  api_secret: ''
